### ISSUE TITLE
Test of memory leak

### ISSUE THREAD

**Issue by lofidewanto** [interseroh/report-cockpit-birt-web#13]
I feel that the report webapp has memory leak. We need to check this out.

**Comment by idueppe** [comment]
Please provide a heap dump :-)

**Comment by idueppe** [comment]
@lofidewanto did you had time to create a heap dump or doesn't the error show up again?

**Comment by lofidewanto** [comment]
I still get OOME.

Here is a tip: https://lbroudoux.wordpress.com/2011/03/06/limit-birt-heap-usage-to-avoid-outofmemoryerror

**Comment by lofidewanto** [comment]
Michael has fixed this. If you are using Oracle JDBC you should use the latest one JDBC 7. It helps.
