### ISSUE TITLE
Create authorization for the security

### ISSUE THREAD

**Issue by lofidewanto** [interseroh/report-cockpit-birt-web#14]
We already have authentification with Spring Sercurity. We also need simple authorization.

**Comment by lofidewanto** [comment]
Here is the entities and services class diagram: https://raw.githubusercontent.com/interseroh/report-cockpit-birt-web/master/src/main/resources/model/report-cockpit-birt.jpg

**Comment by lofidewanto** [comment]
We still need following:

1. Add an example user "lofidewanto" into the database with the help of Flyway for following role: USER.

2. Add hasRole or UserInRole in the correct controller, see: http://www.baeldung.com/spring-security-expressions-basic

**Comment by lofidewanto** [comment]
1. Flyway inserted, see Test (IT): MigrationDatabaseIT

2. hasRole: we need to use the reportName. For example: hasRole("salesinvoice"), see DatabaseLdapAuthoritiesPopulator

**Comment by lofidewanto** [comment]
Open: I'm not sure whether we need Many-To-Many relationships between: Role and Report. At the moment only One-To-Many: https://github.com/interseroh/report-cockpit-birt-web/blob/master/src/main/resources/model/report-cockpit-birt.jpg

**Comment by idueppe** [comment]
Roles are now checked and an exception occurs if the user do not have the needed role. 
Now we only need a nice error message that informs the user of missing privilege. 

@holgerhopf, implement an error handling that leads the user back to `/reports` with a message that he does not have the permission to see the report.

**Comment by lofidewanto** [comment]
Works, I need to update the SQL scripts since you need ONE role for EACH report. See: https://github.com/interseroh/report-cockpit-birt-web/blob/master/src/main/resources/db/migration/V2__Add_users.sql

Still open just what @idueppe said: no error handling

**Comment by idueppe** [comment]
Done

**Comment by pacscam** [comment]
Hello Guys, sorry to bother you but, I'm trying to build this interesting  app, but looks like we missing this two classes:
UserRole
UserService

So where I can Find it ?

**Comment by lofidewanto** [comment]
Those classes will be generated automatically with the help of our generator: KissMDA: https://github.com/crowdcode-de/KissMDA

You can see here is our UML model which will be the based to generated the interfaces:
https://github.com/interseroh/report-cockpit-birt-web/tree/master/src/main/resources/model

Just do: mvn generate-sources -- if you want to generate those files.

Hope this helps.

**Comment by pacscam** [comment]
Thank  you Dr. Jawa ! you already help a lot with this codes and thanks again  for your attention but here doesn't work.

Maybe its me doing something wrong... lol

Would like to ask you if could send this two files to my e-mail paulocamargoj@gmail.com

I'm so excited to run this app cuz I'm on this kind o challenge and I believe that it will demonstrate to my boss that works as well

Please...

**Comment by lofidewanto** [comment]
@pacscam Could you please open a new issue ticket? 

I could try to answer your questions in that new ticket. It's good to make it there so that we can learn and could make the thing better...

Thanks a lot.
