### ISSUE TITLE
Maven build seems to be broken on a clean maven run.

### ISSUE THREAD

**Issue by idueppe** [interseroh/report-cockpit-birt-web#17]
While running `mvn clean` and thne `mvn install` I get the following error messages:

```shell
INFO] diagnostic Note: Hibernate JPA 2 Static-Metamodel Generator 4.3.11.Final
[INFO] diagnostic /Users/idueppe/development/git/report-cockpit-birt/src/main/java/de/interseroh/report/auth/DatabaseLdapAuthoritiesPopulator.java:43: error: cannot find symbol
        private UserService userService;
                ^
  symbol:   class UserService
  location: class de.interseroh.report.auth.DatabaseLdapAuthoritiesPopulator
[INFO] diagnostic /Users/idueppe/development/git/report-cockpit-birt/src/main/java/de/interseroh/report/auth/GroupEntity.java:36: error: cannot find symbol
public class GroupEntity extends AbstractPersistable<Long> implements Group {
                                                                      ^
  symbol: class Group
[INFO] diagnostic /Users/idueppe/development/git/report-cockpit-birt/src/main/java/de/interseroh/report/auth/GroupEntity.java:44: error: cannot find symbol
        private Collection<Membership> memberships;
                           ^
...
```

It looks like KissMDA isn't configure correctly...

**Comment by lofidewanto** [comment]
This is a bug from 

<groupId>org.bsc.maven</groupId>
<artifactId>maven-processor-plugin</artifactId>

This plugin does not see my generated directory (target/generated-sources/java) although I already put this into build-helper-plugin.

But it is only INFO anyway, so it does not disturb the generation of the JPA metamodel.

**Comment by lofidewanto** [comment]
After reading this: 

http://docs.jboss.org/hibernate/orm/4.3/topical/html/metamodelgen/MetamodelGenerator.html#_usage_from_the_command_line

I removed "maven-processor-plugin". We just need the standard compiler and I added "target/generated-sources/annotations" in build-helper. That's it, works like before and without error infos.

**Comment by lofidewanto** [comment]
It's now also working by compiling using Java 8 (target and source Java 7).
