### ISSUE TITLE
Locale is not correct

### ISSUE THREAD

**Issue by lofidewanto** [interseroh/report-cockpit-birt-web#4]
In the "old" BIRT-Viewer you can see the date was in German format:
![date-format-old](https://cloud.githubusercontent.com/assets/1212950/8507879/d740ce5a-2256-11e5-8382-34c46070ffc2.png)

In the our BIRT-Viewer the date was in English format:
![date-format-new](https://cloud.githubusercontent.com/assets/1212950/8507878/d73e5792-2256-11e5-921b-4aa417c65381.png)

The old one was correct.

**Comment by idueppe** [comment]
On my machine the date format is correct. I guess the system is using the default locale of the machine. Now the locale is explicitly set on the `IRunAndRenderTask` Object to a locale value hold by  the `LocaleContextHolder` of Spring. The default value is set to english. It is overridden by the browser `accept-header` request header. And that is overridden by `reportengine-language` cookie. And this can set by a request parameter `language` to session scoped value. 

For instance, `http://localhost:8080/report-cockpit-birt-web/reports/salesinvoice?language=de`.

**Comment by lofidewanto** [comment]
Locale is now correct.
