### ISSUE TITLE
The looks of the report is not identical

### ISSUE THREAD

**Issue by lofidewanto** [interseroh/report-cockpit-birt-web#5]
Please take a look at this example:

Old BIRT Viewer:
![format-old](https://cloud.githubusercontent.com/assets/1212950/8507893/5242cb4e-2257-11e5-9465-2e2c687d7fde.png)

New BIRT Viewer:
![format-new](https://cloud.githubusercontent.com/assets/1212950/8507894/656b7838-2257-11e5-881f-29d6fdbe4c49.png)

The new BIRT Viewer looks better, but the Old one is the correct one if you compare it with the PDF file.

**Comment by idueppe** [comment]
It looks like that bootstrap sets all `td` and `th` tags to a `padding-left` and -right value of 0. Now setting the `th` and `td` tags back to `1px`. In Safari, Chrome and Firefox newest version it looks fine.

![report_cockpit_birt](https://cloud.githubusercontent.com/assets/1124763/8933493/6ceed862-3543-11e5-997e-b97307fccacf.png)

**Comment by lofidewanto** [comment]
Still not identical, take a look at the "Salesinvoice". On the top there is a broken line.

**Comment by lofidewanto** [comment]
The report image is hard coded with the webapp name:
/report-cockpit-birt-web/reportimages/design1a2d06d14efdd006181.jpg

/report-cockpit-birt-web -> is the name of the webapp. But this is hard coded.
This should not be the case, since the name of the webapp can be changed.

**Comment by lofidewanto** [comment]
Ahh.. this is my fault. I'm writing a Maven overlay project and I also need to overwrite the *.properties so that all the configs will use my new webapp (overlay webapp).
